PAGE=[
    [
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"",
            npc:"",
            background:"",
            isQuestion:true,
            dialogue:questions[0] 
            //if isQuestion is true, 
            //we are accessing the questions from questions.js
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        }
    ],[
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        }
    ],[
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        }
    ],[
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        },
        {
            place:"Home",
            npc:"",
            background:"",
            isQuestion:false,
            dialogue:""
        }
    ]
]